=== UO301609/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchura, fecha, hora, vueltas, localidad, pais, patrocinador, referencias, fotos, videos, origen, sectores, ganador, podio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>
<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidades CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT origen (longitud, latitud, altitud)>
<!ELEMENT sectores (sector+)>
<!ELEMENT sector (distancia, final, numero)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT final (longitud, latitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidades CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidades CDATA #REQUIRED>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT ganador (piloto, tiempo)>
<!ELEMENT piloto (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo unidades CDATA #REQUIRED>
<!ELEMENT podio (clasificado+)>
<!ELEMENT clasificado (#PCDATA)>
<!ATTLIST clasificado posicion CDATA #REQUIRED>

=== UO301609/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>

    <nombre>Automotodrom Brno</nombre>

    <longitud unidades="metros">5.403</longitud>

    <anchura unidades="metros">15</anchura>

    <fecha>2025-07-20</fecha>

    <hora>14:00:00</hora>

    <vueltas>21</vueltas>

    <localidad>Brno</localidad>

    <pais>República Checa</pais>

    <patrocinador>Tissot</patrocinador>

    <referencias>
        <referencia>https://es.wikipedia.org/wiki/Gran_Premio_de_la_Rep%C3%BAblica_Checa_de_Motociclismo_de_2025</referencia>
        <referencia>https://www.rtve.es/deportes/20250718/gran-premio-republica-checa-motogp-previa-brno/16665279.shtml</referencia>
        <referencia>https://www.flashscore.co/motociclismo/motogp/brno</referencia>
    </referencias>

    <fotos>
        <foto>../multimedia/Brno1.png</foto>
        <foto>../multimedia/Brno2.png</foto>
        <foto>../multimedia/Brno3.png</foto>
    </fotos>

    <videos>
        <video>../multimedia/Brno.mp4</video>
    </videos>

    <origen>
        <longitud unidades="grados">16.446E</longitud>        
        <latitud unidades="grados">49.203N</latitud>
        <altitud unidades="metros">440</altitud>
    </origen>

    <sectores>
        <sector>
            <distancia unidades="metros">238.84</distancia>
            <final>
                <longitud unidades="grados">16.44806</longitud>
                <latitud unidades="grados">49.20194</latitud>
                <altitud unidades="metros">440.03</altitud>
            </final>
            <numero>1</numero>
        </sector>
        <sector>
            <distancia unidades="metros">77</distancia>
            <final>
                <longitud unidades="grados">16.44917</longitud>
                <latitud unidades="grados">49.20194</latitud>
                <altitud unidades="metros">440.53</altitud>
            </final>
            <numero>2</numero>
        </sector>
        <sector>
            <distancia unidades="metros">59.38</distancia>
            <final>
                <longitud unidades="grados">16.44972</longitud>
                <latitud unidades="grados">49.20194</latitud>
                <altitud unidades="metros">439.55</altitud>
            </final>
            <numero>3</numero>
        </sector>
        <sector>
            <distancia unidades="metros">90.88</distancia>
            <final>
                <longitud unidades="grados">16.45000</longitud>
                <latitud unidades="grados">49.20222</latitud>
                <altitud unidades="metros">437</altitud>
            </final>
            <numero>4</numero>
        </sector>
        <sector>
            <distancia unidades="metros">52.4</distancia>
            <final>
                <longitud unidades="grados">16.45028</longitud>
                <latitud unidades="grados">49.20306</latitud>
                <altitud unidades="metros">435.94</altitud>
            </final>
            <numero>5</numero>
        </sector>
        <sector>
            <distancia unidades="metros">41</distancia>
            <final>
                <longitud unidades="grados">16.45056</longitud>
                <latitud unidades="grados">49.20333</latitud>
                <altitud unidades="metros">397.07</altitud>
            </final>
            <numero>6</numero>
        </sector>
        <sector>
            <distancia unidades="metros">40.4</distancia>
            <final>
                <longitud unidades="grados">16.45111</longitud>
                <latitud unidades="grados">49.20333</latitud>
                <altitud unidades="metros">393.68</altitud>
            </final>
            <numero>7</numero>
        </sector>
        <sector>
            <distancia unidades="metros">537.5</distancia>
            <final>
                <longitud unidades="grados">16.45806</longitud>
                <latitud unidades="grados">49.20167</latitud>
                <altitud unidades="metros">386.88</altitud>
            </final>
            <numero>8</numero>
        </sector>
        <sector>
            <distancia unidades="metros">19.1</distancia>
            <final>
                <longitud unidades="grados">16.45833</longitud>
                <latitud unidades="grados">49.20167</latitud>
                <altitud unidades="metros">383.83</altitud>
            </final>
            <numero>9</numero>
        </sector>
        <sector>
            <distancia unidades="metros">35.9</distancia>
            <final>
                <longitud unidades="grados">16.45861</longitud>
                <latitud unidades="grados">49.20194</latitud>
                <altitud unidades="metros">378.64</altitud>
            </final>
            <numero>10</numero>
        </sector>
        <sector>
            <distancia unidades="metros">74</distancia>
            <final>
                <longitud unidades="grados">16.45917</longitud>
                <latitud unidades="grados">49.20250</latitud>
                <altitud unidades="metros">381.49</altitud>
            </final>
            <numero>11</numero>
        </sector>
        <sector>
            <distancia unidades="metros">47</distancia>
            <final>
                <longitud unidades="grados">16.45972</longitud>
                <latitud unidades="grados">49.20278</latitud>
                <altitud unidades="metros">384.4</altitud>
            </final>
            <numero>12</numero>
        </sector>
        <sector>
            <distancia unidades="metros">20</distancia>
            <final>
                <longitud unidades="grados">16.46000</longitud>
                <latitud unidades="grados">49.20278</latitud>
                <altitud unidades="metros">386.35</altitud>
            </final>
            <numero>13</numero>
        </sector>
        <sector>
            <distancia unidades="metros">257</distancia>
            <final>
                <longitud unidades="grados">16.46306</longitud>
                <latitud unidades="grados">49.20167</latitud>
                <altitud unidades="metros">407.24</altitud>
            </final>
            <numero>14</numero>
        </sector>
        <sector>
            <distancia unidades="metros">59</distancia>
            <final>
                <longitud unidades="grados">16.46389</longitud>
                <latitud unidades="grados">49.20167</latitud>
                <altitud unidades="metros">409.41</altitud>
            </final>
            <numero>15</numero>
        </sector>
        <sector>
            <distancia unidades="metros">21.1</distancia>
            <final>
                <longitud unidades="grados">16.46417</longitud>
                <latitud unidades="grados">49.20167</latitud>
                <altitud unidades="metros">410</altitud>
            </final>
            <numero>16</numero>
        </sector>
        <sector>
            <distancia unidades="metros">36.0</distancia>
            <final>
                <longitud unidades="grados">16.46444</longitud>
                <latitud unidades="grados">49.20194</latitud>
                <altitud unidades="metros">411.39</altitud>
            </final>
            <numero>17</numero>
        </sector>
        <sector>
            <distancia unidades="metros">31</distancia>
            <final>
                <longitud unidades="grados">16.46444</longitud>
                <latitud unidades="grados">49.20222</latitud>
                <altitud unidades="metros">412.39</altitud>
            </final>
            <numero>18</numero>
        </sector>
        <sector>
            <distancia unidades="metros">577.2</distancia>
            <final>
                <longitud unidades="grados">16.46000</longitud>
                <latitud unidades="grados">49.20639</latitud>
                <altitud unidades="metros">417.73</altitud>
            </final>
            <numero>19</numero>
        </sector>
        <sector>
            <distancia unidades="metros">35.7</distancia>
            <final>
                <longitud unidades="grados">16.45972</longitud>
                <latitud unidades="grados">49.20667</latitud>
                <altitud unidades="metros">418.56</altitud>
            </final>
            <numero>20</numero>
        </sector>
        <sector>
            <distancia unidades="metros">39.2</distancia>
            <final>
                <longitud unidades="grados">16.45917</longitud>
                <latitud unidades="grados">49.20667</latitud>
                <altitud unidades="metros">419.35</altitud>
            </final>
            <numero>21</numero>
        </sector>
        <sector>
            <distancia unidades="metros">39.1</distancia>
            <final>
                <longitud unidades="grados">16.45889</longitud>
                <latitud unidades="grados">49.20639</latitud>
                <altitud unidades="metros">420.57</altitud>
            </final>
            <numero>22</numero>
        </sector>
        <sector>
            <distancia unidades="metros">96.0</distancia>
            <final>
                <longitud unidades="grados">16.45861</longitud>
                <latitud unidades="grados">49.20556</latitud>
                <altitud unidades="metros">422.87</altitud>
            </final>
            <numero>23</numero>
        </sector>
        <sector>
            <distancia unidades="metros">38.6</distancia>
            <final>
                <longitud unidades="grados">16.45806</longitud>
                <latitud unidades="grados">49.20556</latitud>
                <altitud unidades="metros">424.47</altitud>
            </final>
            <numero>24</numero>
        </sector>
        <sector>
