=== UO301609/sew/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombre, tipo, medio, fecha, hora, tiempo, agencia, descripcion, personas, inicio, referencias, recomendacion, hitos, planimetria, altimetria)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT medio (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo unidades CDATA #REQUIRED>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT inicio (nombre, direccion, coordenadas)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>
<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidades CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidades CDATA #REQUIRED>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre?, descripcion?, coordenadas, distancia, fotografia*, video*)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT planimetria (#PCDATA)>
<!ELEMENT altimetria (#PCDATA)>

=== UO301609/sew/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">

<rutas>

    <!-- 1º RUTA-->
    <ruta>
        <nombre>Ruta de las Ermitas</nombre>
        <tipo>Senderismo</tipo>
        <medio>A pie</medio>
        <fecha>2026-08-14</fecha>
        <hora>09:00:00</hora>
        <tiempo unidades="horas">6</tiempo>
        <agencia>Club del Viajero</agencia>
        <descripcion>Hermosa ruta de senderismo que nos permitirá disfrutar de las vistas más
            impresionantes de la sierra de Atapuerca.</descripcion>
        <personas>Todo el público</personas>
        <inicio>
            <nombre>Ermita de San Jorge</nombre>
            <direccion>Ermita de San Jorge, 09441 Sotillo de la Ribera, Burgos</direccion>
            <coordenadas>
                <longitud unidades="grados">-3.822924900934569</longitud>
                <latitud unidades="grados">41.77709041929234</latitud>
                <altitud unidades="metros">765</altitud>
            </coordenadas>
        </inicio>
        <referencias>
            <referencia>https://turismoburgos.org/pr-ruta-de-las-ermitas/</referencia>
            <referencia>https://www.terranostrum.es/senderismo/sendero-de-las-ermitas</referencia>
            <referencia>https://www.sotillodelaribera.es/rutas/ruta-de-las-ermitas</referencia>
        </referencias>
        <recomendacion>6</recomendacion>
        <hitos>
            <!-- HITO CONOCIDO-->
            <hito>
                <nombre>Ermita de San Jorge</nombre>
                <descripcion> Ubicada en una posición privilegiada, la ermita es un punto destacado
                    para el senderismo y la fotografía, ofreciendo vistas que se extienden hasta la
                    sierra de Atapuerca y los viñedos de la zona. Es considerada una de las
                    principales atracciones del municipio, destacando por su arquitectura sencilla y
                    su entorno tranquilo, ideal para disfrutar de la naturaleza y la historia local. </descripcion>
                <coordenadas>
                    <longitud unidades="grados">-3.822924900934569</longitud>
                    <latitud unidades="grados">41.77709041929234</latitud>
                    <altitud unidades="metros">765</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0</distancia>
                <fotografia>multimedia/Ermita_San_Jorge.jpg</fotografia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.823865572315588</longitud>
                    <latitud unidades="grados">41.77665671518214</latitud>
                    <altitud unidades="metros">768</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.092</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.824447067090539</longitud>
                    <latitud unidades="grados">41.77619287362832</latitud>
                    <altitud unidades="metros">772</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.071</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.825516602662216</longitud>
                    <latitud unidades="grados">41.77644194387533</latitud>
                    <altitud unidades="metros">775</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.093</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.825714887117512</longitud>
                    <latitud unidades="grados">41.77544500097246</latitud>
                    <altitud unidades="metros">777</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.112</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.825979447388252</longitud>
                    <latitud unidades="grados">41.77533279942536</latitud>
                    <altitud unidades="metros">778</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.025</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.826574046073301</longitud>
                    <latitud unidades="grados">41.77534567996856</latitud>
                    <altitud unidades="metros">780</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.049</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.827566302103862</longitud>
                    <latitud unidades="grados">41.77384193844888</latitud>
                    <altitud unidades="metros">780</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.186</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.828684797073265</longitud>
                    <latitud unidades="grados">41.77273345873541</latitud>
                    <altitud unidades="metros">780</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.154</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.830478316426038</longitud>
                    <latitud unidades="grados">41.77194351347693</latitud>
                    <altitud unidades="metros">780</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.173</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.832689874258823</longitud>
                    <latitud unidades="grados">41.7703179986547</latitud>
                    <altitud unidades="metros">779</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.258</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.833981568172393</longitud>
                    <latitud unidades="grados">41.76874392264552</latitud>
                    <altitud unidades="metros">778</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.205</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.834724749216998</longitud>
                    <latitud unidades="grados">41.76826572378202</latitud>
                    <altitud unidades="metros">777</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.081</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.837277193590098</longitud>
                    <latitud unidades="grados">41.76727105772849</latitud>
                    <altitud unidades="metros">776</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.239</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.840619634886387</longitud>
                    <latitud unidades="grados">41.76425062271154</latitud>
                    <altitud unidades="metros">776</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.435</distancia>
            </hito>
            <!-- HITO CONOCIDO-->
            <hito>
                <nombre>Ermita de San Isidro</nombre>
                <descripcion> Construida entre los siglos XVII y XVIII gracias al auge económico de
                    la villa durante el reinado de Carlos III. Ubicada al sur del término municipal
                    junto al arroyo de Sotillo, la ermita se asienta en un pequeño cerro rodeada de
                    almendros, ofreciendo una panorámica característica del paisaje ribereño. </descripcion>
                <coordenadas>
                    <longitud unidades="grados">-3.840636822631505</longitud>
                    <latitud unidades="grados">41.76336729444583</latitud>
                    <altitud unidades="metros">775</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.098</distancia>
                <fotografia>multimedia/Ermita_San_Isidro.jpg</fotografia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.840627307678709</longitud>
                    <latitud unidades="grados">41.76425756650123</latitud>
                    <altitud unidades="metros">775</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.099</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.839524662477314</longitud>
                    <latitud unidades="grados">41.7652843764548</latitud>
                    <altitud unidades="metros">775</altitud>
                </coordenadas>
                <distancia unidades="kilómetros">0.146</distancia>
            </hito>
            <hito>
                <coordenadas>
                    <longitud unidades="grados">-3.841279507867255</longitud>
                    <latitud unidades="grados">41.76525841497521</latitud>
                    <altitud unidades="metros">776</altitud>
                </coordenadas>
